### ISSUE TITLE
 'react/renderer/components/RNCViewPager/ComponentDescriptors.h' file not found

### ISSUE THREAD

**Issue by XFAISAL** [callstack/react-native-pager-view#694] opened 2023-02-19 04:25 UTC
## Environment
RN : 
System:
    OS: macOS 13.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 475.82 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /var/folders/yz/wq4w7w1j4dn2rvmjbmr0g3tw0000gn/T/yarn--1676780598238-0.02454707847026194/node
    Yarn: 1.22.19 - /var/folders/yz/wq4w7w1j4dn2rvmjbmr0g3tw0000gn/T/yarn--1676780598238-0.02454707847026194/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2023.02.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/faisal/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.3 => 0.69.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 4.99s.

POD :

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin22]
    RubyGems : 3.1.6
        Host : macOS 13.2.1 (22D68)
       Xcode : 14.1 (14B47b)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /Users/faisal/.rbenv/versions/2.7.5/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/faisal/.rbenv/versions/2.7.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

target 'MyApp' do
  config = use_native_modules!
  pod 'react-native-webrtc', :path => '../node_modules/@videosdk.live/react-native-webrtc'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

## Description
im trying to use  new New architecture
i already use yarn add react-native-pager-view@newarch

with RCT_NEW_ARCH_ENABLED=1 bundle exec pod install

IOS Build failed with this error : 'react/renderer/components/RNCViewPager/ComponentDescriptors.h' file not found

**Comment by troZee** [comment] 2023-03-02 11:20
1. Please use the latest version of the Pager 
2. Probably codegen did not generate files 
3. before yarn please use `git clean -xdf `
4. please check out our `fabricexample`

**Comment by atultiwaree** [comment] 2024-02-25 11:59
@troZee  I followed fabric example still getting the same issue RNCViewPagerComponentDescriptor.h not found

**Comment by vinamrahalgar** [comment] 2024-04-28 18:30
Any solution?

**Comment by MrRefactor** [comment] 2024-11-29 10:31
Cannot reproduce, closing.

**Closed by MrRefactor** 2024-11-29 10:31 UTC
