### ISSUE TITLE
scrolls pages opposite direction iOS when locale device set to any RTL language

### ISSUE THREAD

**Issue by RodinHatokayTe** [callstack/react-native-pager-view#648] opened 2022-11-17 11:25 UTC
## Environment

iOS

## Description

set the device to RTL language (Hebrew, Arabic), and app in RTL using I18Manager then trying to scroll the pages(tabs), it scrolls the opposite direction.
setting the device to LTR language (en, etc.. ) the component works very well with RTL enabled using I18Manager (ui flipped and everything in RTL ).

issue only reproduces when the device set to any RTL language at iOS device level (not app) 

## Reproducible Demo

download example project,  add all necessary logic to implement RTL (localization in xCode  + set RTL to true ) 
set the local device to any RTL language (Arabic, Hebrew) 
run the example app (the packages provides) 
navigate to ScrollableTabBarExample -> scroll via pages, it scrolls the opposite way

**Comment by troZee** [comment] 2022-11-17 11:34
@RodinHatokayTe could you post a video of your issue ?

**Comment by troZee** [comment] 2022-11-17 12:08
@krozniata changed language to Arabic and I18nManager.isRTL returned false, so it seems `I18nManager` is broken and does not detect if current language is RTL

**Comment by troZee** [comment] 2022-11-17 12:12
https://user-images.githubusercontent.com/12766071/202443176-f82a6aeb-32f5-4336-ab2f-488d06dc85f1.mov

**Comment by RodinHatokayTe** [comment] 2022-11-17 12:18
> RPReplay_Final1668686874.mov
problem occurs when setting to Hebrew, Arabic the device and in app. 

This is when device language set to english it works as should be

https://user-images.githubusercontent.com/87924596/202444084-7ef51b79-596d-49bc-99af-559dd3a20666.mov

**Comment by RodinHatokayTe** [comment] 2022-11-22 08:33
in my personal project it is not resolved even though i bumped to version 6.1.1, i will check later with example in this project.

**Comment by Yasser-G** [comment] 2023-07-09 12:20
@troZee  This bug is not resolved, it is from the native component logic, the following screenshot may help debugging it!

<img width="729" alt="Screen Shot 2023-07-09 at 3 18 45 PM" src="https://github.com/callstack/react-native-pager-view/assets/43137533/2a79be20-3890-4107-a1e3-1e587cc8604b">

**Comment by MrRefactor** [comment] 2024-11-28 07:30
cannot reproduce, closing

**Closed by MrRefactor** 2024-11-28 07:30 UTC
Labels: bug
