### ISSUE TITLE
RTL swipe direction not working on Android

### ISSUE THREAD

**Issue by alwathan** [callstack/react-native-pager-view#767] opened 2023-09-04 23:57 UTC
## Environment

"react-native-pager-view": "^6.2.1",
"react-native": "0.72.4",
"expo": "~49.0.8",

## Description

RTL swipe direction not working on Android.

## This is my script

```javascript
import React from "react";
import {I18nManager, StyleSheet, View, Text } from "react-native";
import PagerView from "react-native-pager-view";

I18nManager.allowRTL(true);
I18nManager.forceRTL(true);
I18nManager.swapLeftAndRightInRTL(true);

const Pager = () => {
  return (
    <PagerView style={styles.pagerView} initialPage={0} layoutDirection={"rtl"}>
      <View key="1">
        <Text>First page</Text>
      </View>
      <View key="2">
        <Text>Second page</Text>
      </View>
    </PagerView>
  );
};

const styles = StyleSheet.create({
  pagerView: {
    flex: 1,
  },
});

export default Pager;
```

## Demo

<img src="https://github.com/callstack/react-native-pager-view/assets/16916624/3534fe0d-969d-45d0-b1c7-3eee8b6f929e" width="250" />

<img src="https://github.com/callstack/react-native-pager-view/assets/16916624/2294e5c9-1edf-47d3-9ada-6d050972b655" width="250" />

**Comment by sepperousseau** [comment] 2023-09-19 09:08
@alwathan Did you add `android:supportsRtl="true"` to your AndroidManifest? For me this fixed the issue.

**Comment by alwathan** [comment] 2023-09-20 16:15
@sepperousseau I am using expo

**Comment by omarZaoujal99** [comment] 2024-01-31 21:53
same here, `layoutDirection="rtl"` not working in android

"expo": "~49.0.13",
"react-native": "0.72.5",
"react-native-pager-view": "6.2.0",

**Comment by hasan642** [comment] 2024-03-07 13:03
no solution yet?
the swipe direction is inverted on Android

**Comment by github-id01** [comment] 2024-04-23 08:33
any solution for this ? Am using expo.

**Comment by blazk0** [comment] 2024-06-29 20:04
swipe direction is inverted on android

**Comment by Selvster** [comment] 2024-08-04 23:19
I added 
` transform: [{ scaleX: -1 }]`, 
to my PagerView & inner views  and set initialPage to max page , and it worked well
`<PagerView style={[styles.pageViewer, {transform: [{ scaleX: -1 }] }]} initialPage={2}`
`<View key={1} style={{ justifyContent: 'center', transform: [{ scaleX: -1 }] }}>
    <TransferRequestCertifying />
  </View>`

**Comment by MrRefactor** [comment] 2024-11-28 06:55
Hey, are you still able to reproduce that issue? I cannot reproduce it in example repository, checked using `layoutDirection={"rtl"}` property. 

https://github.com/user-attachments/assets/4e3b927f-c2b5-4937-8c37-9481299103e9

https://github.com/user-attachments/assets/33a035c0-e85c-4297-ae27-8cabdb82dfbc

**Closed** 2024-11-29 10:36 UTC
