### ISSUE TITLE
Blank screen when swiping pages

### ISSUE THREAD

**Issue by den-rn-dev** [callstack/react-native-pager-view#667] opened 2022-12-06 15:47 UTC
## Environment
"react-native": "0.70.6",
"react-native-pager-view": "6.1.2",

Simulator iPhone 13 mini
iOS 15.5

## Description
Blank screen when swiping pages. After a while, the content appears

## Reproducible Demo
https://user-images.githubusercontent.com/88533263/205957845-5cd95a88-6ef9-4a03-b611-5fad7364878d.mov

```
import React from 'react';
import PagerView from 'react-native-pager-view';
import {View, StyleSheet, Text} from 'react-native';

const App = () => {
  return (
    <PagerView style={styles.pagerView} initialPage={0}>
      <View key="1" style={[styles.page, {backgroundColor: 'red'}]}>
        <Text>FIRST PAGE</Text>
      </View>
      <View key="2" style={[styles.page, {backgroundColor: 'green'}]}>
        <Text>SECOND PAGE</Text>
      </View>
      <View key="3" style={[styles.page, {backgroundColor: 'yellow'}]}>
        <Text>THIRD PAGE</Text>
      </View>
    </PagerView>
  );
};

const styles = StyleSheet.create({
  pagerView: {
    flex: 1,
  },
  page: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
});

export default App;
```

**Comment by MrRefactor** [comment] 2024-11-28 07:28
Cannot reproduce, closing.

**Closed by MrRefactor** 2024-11-28 07:28 UTC
