### ISSUE TITLE
[Android] Crash: could not find Fragment constructor

### ISSUE THREAD

**Issue by LenaZhuk** [callstack/react-native-pager-view#282] opened 2021-02-08 08:39 UTC
## Environment

"react-native": "0.62.2"
"@react-native-community/viewpager": "^5.0.5"

Devices: Samsung Galaxy A31 (Android 10), Samsung Galaxy A11 (Android 10), Samsung Galaxy J5 (Android 9)

## Description

Crash in Firebase Crashlytics report:

Caused by androidx.fragment.app.Fragment$InstantiationException
Unable to instantiate fragment com.reactnativecommunity.viewpager.ViewPagerFragment: could not find Fragment constructor

## Stack trace

Caused by androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.reactnativecommunity.viewpager.ViewPagerFragment: could not find Fragment constructor
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
       at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
       at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
       at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:44)
       at com.ellorem.oxygean.MainActivity.onCreate(MainActivity.java:15)
       at android.app.Activity.performCreate(Activity.java:7963)
       at android.app.Activity.performCreate(Activity.java:7952)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by troZee** [comment] 2021-02-08 09:16
Hey @LenaZhuk 
Thank you for reporting an issue. Do you know, how to reproduce it ?

**Comment by LenaZhuk** [comment] 2021-02-08 09:28
@troZee Hi, as described, this is from the firebase crashlytics report, so I have only a stack trace.

Some context:
The ViewPager is the main component that is used to display the video feed to our users. So the app displays it right after the splash screen (almost at launch).

**Comment by manuhook** [comment] 2021-03-17 11:08
Same issue reported on firebase

`Caused by androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.reactnativepagerview.ViewPagerFragment: could not find Fragment constructor
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:538)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManagerImpl$6.instantiate(FragmentManagerImpl.java:2851)
       at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:85)
       at androidx.fragment.app.FragmentManagerImpl.restoreSaveState(FragmentManagerImpl.java:2488)
       at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:195)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:288)
       at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
       at com.reactnativenavigation.NavigationActivity.onCreate(NavigationActivity.java:36)
       at com.cookomix.mobile.MainActivity.onCreate(MainActivity.java:12)
       at android.app.Activity.performCreate(Activity.java:8086)
       at android.app.Activity.performCreate(Activity.java:8074)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)`

I have not yet found a way to reproduce the crash.

It is used with https://github.com/satya164/react-native-tab-view (and react-native-navigation)

**Comment by troZee** [comment] 2021-03-17 11:21
> Same issue reported on crashlytics (with react-native-pager-view 5.1.2)
> 
> Caused by androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.reactnativepagerview.ViewPagerFragment: could not find Fragment constructor
> at androidx.fragment.app.Fragment.instantiate(Fragment.java:538)
> at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
> at androidx.fragment.app.FragmentManagerImpl$6.instantiate(FragmentManagerImpl.java:2851)
> at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:85)
> at androidx.fragment.app.FragmentManagerImpl.restoreSaveState(FragmentManagerImpl.java:2488)
> at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:195)
> at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:288)
> at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
> at com.reactnativenavigation.NavigationActivity.onCreate(NavigationActivity.java:36)
> at com.cookomix.mobile.MainActivity.onCreate(MainActivity.java:12)
> at android.app.Activity.performCreate(Activity.java:8086)
> at android.app.Activity.performCreate(Activity.java:8074)
> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
> at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
> at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
> at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
> at android.os.Handler.dispatchMessage(Handler.java:107)
> at android.os.Looper.loop(Looper.java:213)
> at android.app.ActivityThread.main(ActivityThread.java:8178)
> at java.lang.reflect.Method.invoke(Method.java)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)`
> 
> I have not yet found a way to reproduce the crash. It seems to be when the app starts.
> 
> It is used with https://github.com/satya164/react-native-tab-view (and react-native-navigation)

Are you using expo in your project ?

**Comment by manuhook** [comment] 2021-03-17 11:49
> Are you using expo in your project ?

Hi @troZee No, expo is not used on our project

**Comment by troZee** [comment] 2021-03-17 11:52
> > Are you using expo in your project ?
> 
> Hi @troZee No, expo is not used on our project

I see, could you fork pager-view repo and add additional reproducible example ? Have you experienced this issue on physical device ?

**Comment by manuhook** [comment] 2021-03-17 12:03
For the moment I didn't found a way to reproduce the problem. I've got it only once on my device (samsung galaxy s4) but impossible to reproduce after.

Here's some info on the issue on physical device from my users : 
![Capture d’écran 2021-03-17 à 12 54 32](https://user-images.githubusercontent.com/531834/111463637-17077500-8720-11eb-8be9-f6b8d997979e.png)
![Capture d’écran 2021-03-17 à 12 54 17](https://user-images.githubusercontent.com/531834/111463643-17a00b80-8720-11eb-8083-e0d2b2026e68.png)

Before using react-native-tab-view 3.0.0  I was using "@react-native-community/viewpager": "^4.2.1" in our app on a deep screen with no problem.
After updating to react-native-tab-view 3.0.0, viewpager is call soon after the app is launched (on a react-native-navigation bottomtab - I've try to delay the bottomtab with viewpager using tabsAttachMode: afterInitialTab (https://wix.github.io/react-native-navigation/docs/bottomTabs#controlling-tab-loading) but no improvement)

**Comment by manuhook** [comment] 2021-03-19 07:47
some additional info : 
- this problem affects about 8% of my android users (out of a total of 1M android users)
- the issue can affect the same user several time.
- I still haven't found a way to reproduce the problem :-/
- reverting to react-native-tab-view 2.x and using react-native-pager-view 5.1.2 on a deep screen in our app : the problem is the same. So it's not linked to the fact react-native-pager-view is mounted on a screen early in our app.
- reverting to react-native-pager-view 4.2.4 : no more problems.

**Comment by adlee116** [comment] 2021-06-28 15:37
You will most likely see this issue when rotating the screen when this page is instantiated. It is trying to recreate the view when you have a constructor that requires arguments.

**Comment by mikeqcp** [comment] 2021-07-23 08:35
I'm not able to reproduce it, but it's likely to be fixed by #404, because new implementation doesn't use Fragments anymore.

**Comment by manuhook** [comment] 2021-07-23 08:39
Thank you mike I will update quickly to try again

**Comment by troZee** [comment] 2021-07-26 15:43
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.0

**Closed by troZee** 2021-07-26 15:43 UTC
Labels: android, bug
