### ISSUE TITLE
No command found with name "setScrollEnabledImperatively" on iOS

### ISSUE THREAD

**Issue by naquilini** [callstack/react-native-pager-view#704] opened 2023-03-23 13:53 UTC
## Environment

System:
MacOS 12.6

Node: v14.12.0
React-native: 0.67.5

## Description

After upgrading the `react-native-pager-view` library from `6.0.2` to `6.1.4`, on iOS I'm getting the following error when I try to move to the next page.
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-23 at 14 13 59](https://user-images.githubusercontent.com/56993219/227218738-cb363d23-d6ff-460a-86d4-7ba6e6562974.png)

I think in order to fix it would be enough to rename the `setScrollEnabled` method in `ReactViewPagerManager.m`

```
@@ -63,7 +63,7 @@
     [self goToPage:reactTag index:index animated:false];
 }
 
-RCT_EXPORT_METHOD(setScrollEnabled
+RCT_EXPORT_METHOD(setScrollEnabledImperatively
                   : (nonnull NSNumber *)reactTag enabled
                   : (nonnull NSNumber *)enabled) {
     BOOL isEnabled = [enabled boolValue];

```

**Comment by alzalabany** [comment] 2023-05-08 17:13
same on 6.1.4

**Comment by okwasniewski** [comment] 2023-07-17 14:46
Hello @naquilini,

Did you re-run `pod install`? Because it looks like JS got out of sync with native dependency.

**Comment by MrRefactor** [comment] 2024-11-29 10:33
Cannot reproduce, closing.

**Closed by MrRefactor** 2024-11-29 10:33 UTC
