### ISSUE TITLE
initial page render question

### ISSUE THREAD

**Issue by baesumin** [callstack/react-native-pager-view#400] opened 2021-07-22 07:54 UTC
## Ask your Question

when PagerView rendered, 
even though the initialPage={1} is selected, Page 0 is displayed first then Page 1 is displayed.
i use Android simulator. help!

**Comment by troZee** [comment] 2021-07-22 08:33
Hello 👋 
Thank you for reporting an issue. How about the ios ?

**Comment by baesumin** [comment] 2021-07-22 09:54
> Hello 👋
> Thank you for reporting an issue. How about the ios ?

I haven't tried ios yet.

**Comment by troZee** [comment] 2021-07-22 11:37
I am not able to reproduce it, hence I am closing this issue

**Comment by baesumin** [comment] 2021-07-23 01:22
i think same problems in android ..
https://www.gitmemory.com/issue/react-native-community/react-native-viewpager/101/553832372
https://github.com/callstack/react-native-pager-view/issues/190

**Comment by rajeshde** [comment] 2021-07-26 12:03
Will this fix be on a new release version soon?

**Closed** 2021-07-26 12:36 UTC
Labels: android, bug

**Comment by troZee** [comment] 2021-07-26 12:38
@rajeshde https://github.com/callstack/react-native-pager-view/releases/tag/v5.3.3

**Comment by tx-techxpert** [comment] 2021-07-29 13:24
still not working for me

**Comment by phuocantd** [comment] 2021-08-01 16:26
> still not working for me

same to you

**Comment by troZee** [comment] 2021-08-02 13:12
I am not able to reproduce that 

https://user-images.githubusercontent.com/12766071/127867430-939f9bc1-2ab6-41b1-b85e-f7ecaada0766.mov

**Comment by troZee** [comment] 2021-08-03 09:29
is it refers to this issue ? https://github.com/callstack/react-native-pager-view/issues/409

**Comment by skipness** [comment] 2021-08-06 07:05
Maybe it's about using state to store the `initialIndex`? I found that if I use state to store the index, pager will render page 0 first then jump to page 3
```js
// BasicPagerViewExample.js
export function BasicPagerViewExample() {
  const { ref, ...navigationPanel } = useNavigationPanel();
  const [index, setIndex] = useState(0);
  useEffect(() => {
    setIndex(3)
  }, []);

  return (
    <SafeAreaView style={styles.container}>
      <AnimatedPagerView
        //@ts-ignore
        testID="pager-view"
        ref={ref}
        style={styles.PagerView}
        initialPage={index}
       .......
```

but if I set initialPage like this: `initialPage={3}` or using `useLayoutEffect` to set the index, pager will set to third page on first rendering

https://user-images.githubusercontent.com/8035517/128470055-7ff54522-963f-4dd0-ac58-d3bb9a1ad5b8.mp4

**Comment by troZee** [comment] 2021-08-09 13:49
Why do you store the initial index in state ? It is incorrect ? Please take a look on the example https://github.com/callstack/react-native-pager-view/blob/master/example/src/BasicPagerViewExample.tsx

**Comment by phuocantd** [comment] 2021-08-31 04:07
@troZee when I set initialPage={2} (in example https://github.com/callstack/react-native-pager-view/blob/master/example/src/BasicPagerViewExample.tsx) then It start with page 0 to page 2. You can view it in below video
I using "react-native-pager-view": "^5.1.10",


https://user-images.githubusercontent.com/31690470/131440080-b271c4c5-acc1-4eec-b46c-fb56e8425be7.mp4

**Comment by phuocantd** [comment] 2021-08-31 07:26
> Why do you store the initial index in state ? It is incorrect usage. Please take a look on the example https://github.com/callstack/react-native-pager-view/blob/master/example/src/BasicPagerViewExample.tsx

how to add first page and remove first page?

**Comment by kyunkakata** [comment] 2022-02-25 09:29
I also suffered this problem and have already created a pull request to fix this problem in Android. Please take a look https://github.com/callstack/react-native-pager-view/pull/521
