### ISSUE TITLE
Unable to resolve module @babel/runtime/helpers/interopRequireDefault

### ISSUE THREAD

**Issue by ignacioscl** [callstack/react-native-pager-view#739] opened 2023-07-09 02:50 UTC
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.pagerviewexample/.MainActivity }
 BUNDLE  ./index.js

error: Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from C:\z\ReactNative\mis_ejemplos\react-native-pager-view\src\PagerView.tsx: @babel/runtime/helpers/interopRequireDefault could not be found within the project.
> 1 | import React from 'react';
  2 | import { Platform, Keyboard } from 'react-native';
  3 | import { I18nManager } from 'react-native';
  4 | import type {

I tried to start the example using all these versions of Node:
18.11.0 (Currently using 64-bit executable)
17.0.0
16.16.0
14.17.5
12.9.1

But the error is always the same. The solutions found on the internet for @babel/runtime/helpers/interopRequireDefault did not solve this problem.

I don't know how to successfully execute "npm start" on Android.

**Comment by huiqun922** [comment] 2023-09-11 11:00
cd  react-native-pager-view

yarn install  & yarn example android

**Comment by MrRefactor** [comment] 2024-11-29 10:32
Cannot reproduce, closing.

**Closed by MrRefactor** 2024-11-29 10:32 UTC
Labels: question
