### ISSUE TITLE
[TS] PagerView typescript is broken

### ISSUE THREAD

**Issue by AlirezaHadjar** [callstack/react-native-pager-view#823] opened 2024-05-03 15:36 UTC
## Description

I just noticed that in the latest version, the typescript of this package is not working as expected.

## Reproducible Demo

1. Create a ref:
```tsx
const ref = useRef<PagerView>(null);
```
Now you will get this ts error: `'PagerView' refers to a value, but is being used as a type here. Did you mean 'typeof PagerView'`

![Screenshot 2024-05-03 at 7 06 04 PM](https://github.com/callstack/react-native-pager-view/assets/57192409/7e541bf4-9f15-4312-9355-b606807c1929)

**Comment by renchap** [comment] 2024-05-03 18:10
I can reproduce this with 6.3.1, while it works with 6.3.0. 

https://github.com/callstack/react-native-pager-view/pull/817 has been merged and is in the `v6.3.1` tag which I think it a mistake, because it means that 6.3.1 is in equivalent to 7.0.0-rc2?

Pining @troZee here because I do not think this was your intent at all!

**Comment by asusoft** [comment] 2024-05-08 14:24
any fix??

**Comment by sergeymild** [comment] 2024-05-15 05:35
The same error

**Comment by Jonnboy91** [comment] 2024-05-15 06:15
I came across this same issue as well. Noticed that on iOS it still seemed to work even with the typescript complaints, but Android was not working anymore on the screens that uses this.

As mentioned previously locking the version to 6.3.0 works.

**Comment by DrRefactor** [comment] 2024-05-21 07:00
@troZee I'm not @MrRefactor but funny enough, "almost am" (look at the nicknames). Please see my PR:
https://github.com/callstack/react-native-pager-view/pull/827

**Closed** 2024-05-22 06:51 UTC

**Comment by renchap** [comment] 2024-05-22 07:25
This is fixing `main`, but you still published a patch release (6.3.1) with the content of `main`, which makes it equivalent to a major 7.0.0 release.

**Comment by gottfriedaniel** [comment] 2024-06-02 09:38
When you'll release this fix?
