### ISSUE TITLE
Cannot Compile ReactNativePageView.m

### ISSUE THREAD

**Issue by AliYar-Khan** [callstack/react-native-pager-view#724] opened 2023-05-11 19:31 UTC
## Ask your Question

I am running ios app and it is giving me this error
```
The following build commands failed:
	CompileC /Users/gill/Library/Developer/Xcode/DerivedData/CardToGo-btkcslzhbtwebufeaeebbsovyves/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-pager-view.build/Objects-normal/arm64/ReactNativePageView.o /Users/gill/Development/cardtogo-react-native/node_modules/react-native-pager-view/ios/ReactNativePageView.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-pager-view' from project 'Pods')
(1 failure)
```

my pods file is as follows

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# 
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

pod 'Firebase', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'RNFBApp', path:'../node_modules/@react-native-firebase/app/RNFBApp.podspec'
target 'CardToGo' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    # :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'CardToGoTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

How can i solve this ? PLease need answer

**Comment by Pluvas159** [comment] 2023-07-17 08:41
i have the same problem

**Comment by Poscholars** [comment] 2023-10-21 02:18
Please any fix I am experiencing the same problem

**Comment by MrRefactor** [comment] 2024-11-29 10:33
Cannot reproduce, closing.

**Closed by MrRefactor** 2024-11-29 10:33 UTC
Labels: question
