### ISSUE TITLE
Problem with Android build - 6.1.4.

### ISSUE THREAD

**Issue by dsound-zz** [callstack/react-native-pager-view#697] opened 2023-03-08 21:57 UTC
## When trying to run react-native android, I get a build error referring to an issue with Kotlin compileSdkVersion. The error looks like this:

```

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\Users\dsims\projects\ocr-mobile2\node_modules\react-native-pager-view\android\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':react-native-pager-view'.
> Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-pager-view'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 17s
```

## Reproducible Demo

1.  React Native 0.67.5
2. Gradle 8.0
3. react-native-pager-view 6.1.4
4. current Kotlin in Android Studio: 221-1.8.0-release-for-android-studio-AS5591.52

run` npx react-native android `or in android folder, run` ./gradlew clean` or `./gradlew build`

**Comment by neon010** [comment] 2023-03-11 14:21
I am also geting same error. does anyone have figured out solution ?

**Comment by neon010** [comment] 2023-03-17 14:08
I solved this issue by switching the version of react-native-pager-view to 6.0.1. This build crashing is only happening  in lattest version

**Comment by arjuntsaji** [comment] 2023-11-28 18:05
You just need to set kotlinVersion in your project level build.gradle in the ext section

Like this:

![WhatsApp Image 2023-11-28 at 11 30 25 PM](https://github.com/callstack/react-native-pager-view/assets/80873802/90b53c2c-51f1-4bc1-a982-90b43b8538e3)

**Comment by Mohamed-Raid** [comment] 2023-12-13 10:24
same issue

**Comment by MrRefactor** [comment] 2024-11-28 07:25
Cannot reproduce, closing.

**Closed by MrRefactor** 2024-11-28 07:25 UTC
